### PR TITLE
feat: haproxyType

### PR DESCRIPTION
**Pull request by olinkl**
Signed-off-by: Adrien Bensaïbi <adrien.bensaibi@corp.ovh.com>

### CODE REVIEW

**Comment by d33d33** [comment]
Why do you want to map HaProxy type to strings?

**Comment by yadutaf** [comment]
It helps with discovery. When the user crawls his data for the first time like when creating a dashboard, he is likely to dismiss informations of the form "type=number", this looks like low entropy debug information until / unless you read the HAProxy ops docs in depth

**Comment by d33d33** [comment]
Ok, understanding the onboarding issue.

Regarding the implementation using a lookup map is pretty expensive.

What about a dense switch statement?
```
t := ""
switch value[0] {
   case '0':
       t = "frontend"
   case '1':
       t = "backend"
   case '2':
       t = "server"
   case '3':
       t = "listen"
}
```

**Comment by olinkl** [comment]
Indeed, a hash is more readable (for me) but trade for a switch statement should be more memory efficient, i could do that.

**Pull request closed without merging**
